2022-09-01 21:31:13,823 INFO    StreamThr :15820 [internal.py:wandb_internal():93] W&B internal server running at pid: 15820, started at: 2022-09-01 21:31:13.822168
2022-09-01 21:31:13,826 DEBUG   HandlerThread:15820 [handler.py:handle_request():141] handle_request: status
2022-09-01 21:31:13,829 DEBUG   SenderThread:15820 [sender.py:send_request():316] send_request: status
2022-09-01 21:31:13,831 INFO    WriterThread:15820 [datastore.py:open_for_write():75] open: /home/pzh/Jitor_Compare/pytorch-CycleGAN-and-pix2pix/wandb/offline-run-20220901_213113-24ai9f93/run-24ai9f93.wandb
2022-09-01 21:31:13,935 DEBUG   HandlerThread:15820 [handler.py:handle_request():141] handle_request: run_start
2022-09-01 21:31:13,943 DEBUG   HandlerThread:15820 [meta.py:__init__():35] meta init
2022-09-01 21:31:13,943 DEBUG   HandlerThread:15820 [meta.py:__init__():50] meta init done
2022-09-01 21:31:13,944 DEBUG   HandlerThread:15820 [meta.py:probe():216] probe
2022-09-01 21:31:13,950 DEBUG   HandlerThread:15820 [meta.py:_setup_git():206] setup git
2022-09-01 21:31:13,969 DEBUG   HandlerThread:15820 [meta.py:_setup_git():213] setup git done
2022-09-01 21:31:13,969 DEBUG   HandlerThread:15820 [meta.py:_save_pip():54] save pip
2022-09-01 21:31:13,970 DEBUG   HandlerThread:15820 [meta.py:_save_pip():68] save pip done
2022-09-01 21:31:13,970 DEBUG   HandlerThread:15820 [meta.py:probe():254] probe done
2022-09-01 21:31:28,522 DEBUG   HandlerThread:15820 [handler.py:handle_request():141] handle_request: partial_history
2022-09-01 21:31:28,590 DEBUG   HandlerThread:15820 [handler.py:handle_request():141] handle_request: partial_history
2022-09-02 03:14:44,565 INFO    MainThread:15820 [internal.py:handle_exit():80] Internal process exited
2022-09-02 03:14:44,567 WARNING MsgRouterThr:15820 [router.py:message_loop():73] EOFError seen in message_loop
